# Generated by Django 2.1.14 on 2019-11-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=140)),
                ('apellidos', models.CharField(max_length=140)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=140)),
                ('carrera', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=140)),
            ],
        ),
    ]
